language: node_js
node_js:
  - '10.13'
services:
  - mongodb
cache: false
env:
  global:
    - CC_TEST_REPORTER_ID=3c185c43a92d448df2cdaade234ab3792c88ba2b57f3316d465201f44cbbcaf5

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm install
  - npm run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls

notifications:
  email: true
